import {buildDocumentPreview} from '../lib/document-preview.mjs';
import {readDraft,saveDraft,deleteDraft} from './draft-store.mjs';
const $=selector=>document.querySelector(selector),esc=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const login='offline-trial',jobId='00000000-0000-4000-8000-000000000001';
let state={job:{jobNo:'',vessel:'',port:'',terminal:'',eta:'',principal:''},people:[],drafts:{},preferences:{}},version=0,options,type='oktb',busy=Promise.resolve();
const jobFields=[['jobNo','Job No.'],['vessel','Vessel'],['port','Port'],['terminal','Terminal'],['eta','ETA','datetime-local'],['principal','Principal']];
const personFields=[['name','Name - Surname'],['nationality','Nationality'],['rank','Rank'],['dob','Date of Birth','date'],['passport','Passport'],['passportExpiry','PP. EXP','date'],['seamanBook','Seaman book'],['surname','Surname'],['givenName','Given name'],['placeOfBirth','Place of Birth'],['passportIssued','Passport issued','date'],['seamanBookIssued','Seaman book issued','date']];
const flightFields=[['airline','Airline'],['number','Flight No.'],['date','Date'],['from','From'],['to','To'],['departure','Departure'],['arrival','Arrival'],['booking','PNR']];
function capture(){if(!options)return;const snapshot=window.HarborFlowDocuments.snapshot(options);state.drafts[type]=snapshot.draft;state.preferences=snapshot.preferences;}
function renderInputs(){
 $('#jobFields').innerHTML=jobFields.map(([key,label,inputType])=>`<label>${label}<input data-job="${key}" type="${inputType||'text'}" maxlength="200" value="${esc(state.job[key])}"></label>`).join('');
 $('#people').innerHTML=state.people.map(p=>`<details open><summary>${esc(p.data.name||'คนใหม่')}</summary><div class="toolbar"><label>ประเภท<select data-person="${p.id}" data-field="category">${['On-signers','Off-signers'].map(c=>`<option ${c===p.data.category?'selected':''}>${c}</option>`).join('')}</select></label><button data-remove-person="${p.id}">ลบคน</button></div><div class="scroll"><table><thead><tr>${personFields.map(([,label])=>`<th>${label}</th>`).join('')}</tr></thead><tbody><tr>${personFields.map(([key,,inputType])=>`<td><input aria-label="${key}" data-person="${p.id}" data-field="${key}" type="${inputType||'text'}" maxlength="200" value="${esc(p.data[key])}"></td>`).join('')}</tr></tbody></table></div><h3>Flight details</h3><div class="scroll"><table><thead><tr>${flightFields.map(([,label])=>`<th>${label}</th>`).join('')}<th>แถว</th></tr></thead><tbody>${p.data.flights.map((flight,i)=>`<tr>${flightFields.map(([key])=>`<td><input aria-label="Flight ${key}" data-flight-person="${p.id}" data-flight="${i}" data-field="${key}" maxlength="100" value="${esc(flight[key])}"></td>`).join('')}<td><button data-remove-flight="${p.id}" data-index="${i}">ลบ</button></td></tr>`).join('')}</tbody></table></div><button data-add-flight="${p.id}">+ เพิ่ม Flight</button></details>`).join('');
}
async function mount(){
 window.HarborFlowDocuments.clear();
 options={type,login,jobId,initialDraft:state.drafts[type],localTransport:{get:async params=>{
 if(params.action==='preferences')return {login,preferences:state.preferences,canSave:true};
 if(params.action==='permitDefaults')return {login,defaults:{agent:[],staff:[],car:[]},version:0};
 if(params.action!=='preview')throw Error('Offline ไม่รองรับคำขอนี้');
 const preview=buildDocumentPreview(params.type,{id:jobId,data:state.job},state.people,[],{crewDetails:true,visitorDetails:true});preview.notice='ร่าง Offline จากข้อมูลสมมติบนเครื่อง · ไม่ได้ตรวจสิทธิ์ปัจจุบัน ไม่ใช่เอกสารอนุมัติ';return {login,preview};
 }}};
 await window.HarborFlowDocuments.mount($('#document'),options);
 const notice=document.createElement('p');notice.className='hfd-warning';notice.textContent='ร่างบนเครื่องเท่านั้น · ไม่มีการซิงค์หรือส่งข้อมูลขึ้นเซิร์ฟเวอร์ กดบันทึกร่างเพื่อเก็บในเครื่อง';$('#document').prepend(notice);
 $('#document').querySelector('#hfdSaveStatus').textContent='ยังไม่ได้บันทึกร่างบนเครื่อง';
}
function schedule(){busy=busy.then(mount).catch(error=>{$('#status').textContent=error.message;});return busy;}
document.addEventListener('change',event=>{const t=event.target;if(t.dataset.job){capture();state.job[t.dataset.job]=t.value;schedule();}else if(t.dataset.person){capture();const p=state.people.find(p=>p.id===t.dataset.person);p.data[t.dataset.field]=t.value;schedule();}else if(t.dataset.flightPerson){capture();const p=state.people.find(p=>p.id===t.dataset.flightPerson);p.data.flights[Number(t.dataset.flight)][t.dataset.field]=t.value.toUpperCase();t.value=t.value.toUpperCase();schedule();}});
$('#type').addEventListener('change',async()=>{await busy;capture();type=$('#type').value;schedule();});
$('#addPerson').addEventListener('click',()=>{capture();state.people.push({id:crypto.randomUUID(),kind:'crew',data:{category:'On-signers',name:'',flights:[]}});renderInputs();schedule();});
$('#people').addEventListener('click',event=>{const t=event.target.closest('button');if(!t)return;capture();if(t.dataset.removePerson)state.people=state.people.filter(p=>p.id!==t.dataset.removePerson);if(t.dataset.addFlight)state.people.find(p=>p.id===t.dataset.addFlight).data.flights.push({});if(t.dataset.removeFlight)state.people.find(p=>p.id===t.dataset.removeFlight).data.flights.splice(Number(t.dataset.index),1);renderInputs();schedule();});
$('#save').addEventListener('click',async()=>{try{await busy;if(!$('#ack').checked)throw Error('ยืนยันการใช้ข้อมูลสมมติก่อนบันทึก');capture();const row=await saveDraft(state,version);version=row.version;$('#status').textContent='บันทึกร่างบนเครื่องแล้ว · ไม่มีการซิงค์ · หมดอายุ '+new Date(row.expiresAt).toLocaleString('th-TH');}catch(error){$('#status').textContent=error.message;}});
$('#load').addEventListener('click',async()=>{try{await busy;const row=await readDraft();if(!row){$('#status').textContent='ไม่มีร่าง หรือร่างหมดอายุแล้ว';return;}if(!confirm('เปิดร่างที่บันทึกไว้? การแก้ที่ยังไม่บันทึกจะถูกแทนที่'))return;state=row.payload;version=row.version;renderInputs();await schedule();$('#status').textContent='เปิดร่างบนเครื่องแล้ว';}catch(error){$('#status').textContent=error.message;}});
$('#remove').addEventListener('click',async()=>{try{if(!confirm('ลบร่างที่บันทึกและข้อมูลในฟอร์มบนเครื่องนี้?'))return;await busy;await deleteDraft();version=0;state={job:{},people:[],drafts:{},preferences:{}};$('#ack').checked=false;renderInputs();await schedule();$('#status').textContent='ลบร่างและข้อมูลในฟอร์มแล้ว (ไฟล์ PDF ที่ดาวน์โหลดต้องลบเอง)';}catch(error){$('#status').textContent=error.message;}});
function connection(){$('#connection').textContent=navigator.onLine?'Online · ฟอร์มนี้ยังเป็นร่างบนเครื่อง ไม่เชื่อมฐานข้อมูล':'Offline · กรอกและสร้าง PDF บนเครื่องได้';}window.addEventListener('online',connection);window.addEventListener('offline',connection);
renderInputs();connection();await schedule();
try{const row=await readDraft();if(row)$('#status').textContent='มีร่างที่บันทึกไว้บนเครื่อง · ต้องเปิดร่างก่อนบันทึกทับ';}catch(error){$('#status').textContent=error.message;}
try{if(!('serviceWorker'in navigator))throw Error('เบราว์เซอร์นี้ไม่รองรับ Offline');const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});let timer;try{await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('เตรียมไฟล์ไม่สำเร็จ กรุณาเชื่อมต่ออินเทอร์เน็ตแล้วโหลดหน้านี้ใหม่')),15000);})]);}finally{clearTimeout(timer);}$('#ready').textContent='แบบฟอร์มพร้อมใช้ Offline แล้ว · เปิดหน้านี้อย่างน้อยหนึ่งครั้งขณะออนไลน์ ก่อนใช้งานโดยไม่มีอินเทอร์เน็ต';if(registration.waiting)$('#ready').textContent+=' · มีเวอร์ชันใหม่ ปิดแท็บนี้ทั้งหมดแล้วเปิดใหม่เพื่ออัปเดต';}catch(error){$('#ready').textContent='ยังไม่พร้อม Offline: '+error.message;}
